# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-07 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_userrating_id_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='id_course',
            new_name='id_int',
        ),
    ]
