# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-07 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20190407_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='id_int',
        ),
    ]
