# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-07 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_remove_userrating_id_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='id_int_course',
            field=models.IntegerField(default=0, verbose_name='课程ID'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='id_int_user',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
    ]
