# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-07 22:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190405_1545'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0005_auto_20190407_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_int_user', models.IntegerField(default=0, verbose_name='用户ID')),
                ('id_int_course', models.IntegerField(default=0, verbose_name='课程ID')),
                ('id_int_lesson', models.IntegerField(default=0, verbose_name='章节ID')),
                ('id_int_video', models.IntegerField(default=0, verbose_name='视频ID')),
                ('time', models.IntegerField(default=0, verbose_name='观看时长(秒)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '观看时长',
                'verbose_name_plural': '观看时长',
            },
        ),
    ]
