# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-11 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_watchingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchingtime',
            name='add_time',
            field=models.DateTimeField(verbose_name='添加时间'),
        ),
    ]
