# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-11 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_auto_20190411_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchingtime',
            name='timetype',
            field=models.CharField(choices=[('1', '工作日上午'), ('2', '工作日下午'), ('3', '工作日晚间'), ('4', '工作日凌晨'), ('5', '周末上午'), ('6', '周末下午'), ('7', '周末晚间'), ('8', '周末凌晨'), ('9', '无')], default=1, max_length=20, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='watchingtime',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
