# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-11 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20190411_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchingtime',
            old_name='timetype',
            new_name='time_type',
        ),
    ]
