# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-11 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_auto_20190411_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchingtime',
            name='time_type',
        ),
    ]
