# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-11 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0011_watchingtime_time_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchingtime',
            name='time_type',
            field=models.CharField(choices=[('1', '工作日上午'), ('2', '工作日下午'), ('3', '工作日晚间'), ('4', '工作日凌晨'), ('5', '周末上午'), ('6', '周末下午'), ('7', '周末晚间'), ('8', '周末凌晨'), ('9', '无')], default=1, max_length=20, verbose_name='时间类别'),
        ),
    ]
