# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-04 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=b'2018-12-04 10:12:25', verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
