# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-23 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
