# Generated by Django 2.0.4 on 2019-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_bannercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'Java'), ('3', 'C/C++'), ('4', 'Android'), ('5', '数据结构'), ('6', '人工智能')], max_length=20, verbose_name='课程类别'),
        ),
    ]
