# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-25 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181025_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='time',
            new_name='title',
        ),
    ]
