# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-31 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181025_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_click',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4fee\u6539'),
        ),
    ]
